# Never daemonize (Docker handles process)
no-daemon

# Don't write PID file
pid-file=

# # Listen on all interfaces
# listen-address=0.0.0.0
# bind-interfaces
# Listen on all interfaces inside container
interface=eth0
listen-address=0.0.0.0

# Enable both UDP and TCP
port=53

# Upstream resolvers (replace if needed)
server=8.8.8.8
server=1.1.1.1

# Cache tuning
cache-size=1000

# Security hardening
domain-needed
bogus-priv
no-resolv

# Logging
log-queries=extra
log-facility=-

# Reduce noise (optional)
# log-async=25

# Load additional config files
conf-dir=/opt/dnsmasq/dnsmasq.conf.d,*.conf
