name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build Docker image
        run: |
          docker build -t dnsmasq-container .

      - name: Run container (detached)
        run: |
          docker run -d \
            --name dnsmasq \
            -p 1053:53/udp \
            -p 1053:53/tcp \
            -v $(pwd)/sample/templates:/opt/dnsmasq/templates \
            dnsmasq-container

      - name: Sleep to allow container to start & healthcheck to run
        run: |
          sleep 15

      - name: Check A records
        run: |
          DEV_RESP=$(dig -p 1053 +tcp +short @127.0.0.1 dev.example.com)
          echo "dev.example.com -> $DEV_RESP"
          [ "$DEV_RESP" = "192.168.0.1" ]

          TEST_RESP=$(dig -p 1053 +tcp +short @127.0.0.1 test.example.com)
          echo "test.example.com -> $TEST_RESP"
          [ "$TEST_RESP" = "192.168.0.2" ]

          PROD_RESP=$(dig -p 1053 +tcp +short @127.0.0.1 prod.example.com)
          echo "prod.example.com -> $PROD_RESP"
          [ "$PROD_RESP" = "192.168.0.3" ]

      - name: Check CNAME record
        run: |
          CNAME_RESP=$(dig -p 1053 +tcp +short @127.0.0.1 CNAME dummy.example.com)
          echo "CNAME dummy.example.com -> $CNAME_RESP"
          [ "$CNAME_RESP" = "prod.example.com." ]

          ALIAS_RESP=$(dig -p 1053 +tcp +short @127.0.0.1 dummy.example.com)
          echo "dummy.example.com -> $ALIAS_RESP"
          [ "$ALIAS_RESP" = "prod.example.com." ]

          TARGET_RESP=$(dig -p 1053 +tcp +short @127.0.0.1 "$ALIAS_RESP")
          echo "$ALIAS_RESP -> $TARGET_RESP"
          [ "$TARGET_RESP" = "192.168.0.3" ]

      - name: Check healthcheck status
        run: |
          STATUS=$(docker inspect --format='{{json .State.Health.Status}}' dnsmasq)
          echo "Container health status: $STATUS"
          [ "$STATUS" = '"healthy"' ]
